# Generated by Django 5.1.7 on 2025-04-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_rename_submitted_at_supportrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
