# Generated by Django 5.1.7 on 2025-04-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_dob_customuser_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
