# Generated by Django 5.1.7 on 2025-04-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_login_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_status',
            field=models.BooleanField(default=True),
        ),
    ]
