# Generated by Django 5.1.7 on 2025-04-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_account_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='account_status',
        ),
    ]
