# Generated by Django 5.1.4 on 2025-02-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
    ]
